# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Department.create(nombre: 'Amazonas')
Department.create(nombre: 'Ancash')
Department.create(nombre: 'Apurimac')
Department.create(nombre: 'Arequipa')
Department.create(nombre: 'Ayacucho')
Department.create(nombre: 'Cajamarca')
Department.create(nombre: 'Cuzco')
Department.create(nombre: 'Huancavelica')
Department.create(nombre: 'Huanuco')
Department.create(nombre: 'Ica')
Department.create(nombre: 'Junin')
Department.create(nombre: 'La Libertad')
Department.create(nombre: 'Lambayeque')
Department.create(nombre: 'Lima')
Department.create(nombre: 'Loreto')
Department.create(nombre: 'Madre de Dios')
Department.create(nombre: 'Moquegua')
Department.create(nombre: 'Pasco')
Department.create(nombre: 'Piura')
Department.create(nombre: 'Puno')
Department.create(nombre: 'San Martin')
Department.create(nombre: 'Tacna')
Department.create(nombre: 'Tumbes')
Department.create(nombre: 'Ucayali')
NumberGuide.create(numero: '000001')
NumberInvoice.create(number: '000001')
Unit.create(nombre: 'Kilogramo', und: 'Kg')
Measure.create(nombre: 'Sacos', und: 'sacos')
Credito.create(nombre: 'Credito a 15 dias')
Moneda.create(nombre: 'Nuevos Soles', simbolo: 'S/.')
Moneda.create(nombre: 'Dolares', simbolo: '$')